// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NarushPDD.InfrastructureServices.Gateways.Database;

namespace NarushPDD.WebService.Migrations
{
    [DbContext(typeof(PDDContext))]
    [Migration("20200521115848_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("NarushPDD.DomainObjects.RoadPDD", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedV")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredV")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoadPDDs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Data = "20.01.2013",
                            RecordedV = "Общее количество зафиксированных нарушений - 5374",
                            RegisteredV = "Общее количество оформленных - 2440"
                        },
                        new
                        {
                            Id = 2L,
                            Data = "21.01.2013",
                            RecordedV = "Общее количество зафиксированных нарушений - 25312",
                            RegisteredV = "Общее количество оформленных - 1551"
                        },
                        new
                        {
                            Id = 3L,
                            Data = "22.01.2013",
                            RecordedV = "Общее количество зафиксированных нарушений - 29132",
                            RegisteredV = "Общее количество оформленных - 2672"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
